[package]
name = "config_path"
version = "0.1.0"
edition = "2021"

[[bin]]
name = 'config_path'
path = 'src/main.rs'

[dependencies]
shellexpand = "2.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0.40"